[build]
target = "riscv64gc-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
runner = "/home/filippo/risc/opt/riscv/sysroot/lib/ld-linux-riscv64-lp64d.so.1 --library-path /home/filippo/risc/opt/riscv/sysroot/lib"
linker = "riscv64-unknown-linux-gnu-gcc"


[profile.release]
opt-level = 0

